### PR TITLE
SMP fix for GHC 8.4 compat

### PR DESCRIPTION
**Pull request by deepfire**

### CODE REVIEW

**Comment by deepfire** [comment]
cc @IagoAbal

**Comment by IagoAbal** [comment]
Thanks!

**Comment by IagoAbal** [comment]
I am not doing much Haskell development nowadays apart from maintaining a couple of small libraries, so I'm not very up-to-date and I'm trusting your good judgment. But to be sure, I'm guessing this change follows https://ghc.haskell.org/trac/ghc/ticket/14191, since there is no base 4.11 yet. Correct?

**Comment by deepfire** [comment]
Somehow `base-4.11` is not on Hackage yet, yes.

However it's part of the `8.4.1` release of GHC: https://github.com/ghc/ghc/blob/ghc-8.4/libraries/base/base.cabal#L3

**Pull request merged**
